#%RAML 1.0 DataType

description: Represents a Session for a speaker
properties:
  id:
    type: integer
  name:
    type: string
  session_description: 
    type: string
  level: 
    type: string
  location_id: 
    type: integer
  event_slot_id: 
    type: integer
  event_slot_name: 
    type: string
  speaker: 
    type: !include speaker.raml