#%RAML 1.0 DataType

description: Represents a Speaker for a session
properties:
  event_id:
    type: integer
  participant_id:
    type: integer
  image_url: 
    type: string
  speaker_bio:
    type: string 
  speaker_url: 
    type: string
  twitter_handle: 
    type: string
  name: 
    type: string
  email: 
    type: string
  tweets: 
    type: array
    items:
      type: !include tweet.raml