#%RAML 1.0 NamedExample
value:
  - 
    id: 1
    name: "Example Session Name"
    session_description: "This is an example description for a session."
    level: "100"
    location_id: 1
    event_slot_name: "9:00 AM - 10:15 AM"
    event_slot_id: 1
    speaker: 
      event_id: 1
      participant_id: 1
      image_url: "https://cdn.shopify.com/s/files/1/0275/1610/8874/files/Richmond_8_b.JPG?v=1604140292"
      speaker_bio: "Joel's Bio here"
      speaker_url: "https://caspershotdogs.com/"
      twitter_handle: "@CaspersJ"
      name: "Joel Caspers"
      email: "joelcaspers@gmail.com"
      tweets: 
        -
          conversation_id?: "1370424763823308807"
          author_id?: "151861092" 
          in_reply_to_user_id: "303364784"
          language?: "en" 
          created_at?: "2021-03-12T18:06:19.000Z"
          text: "@strikeralley Completely agree, especially for the amount they charge for the phones."
          id: "1370436004163817472"
        -
          conversation_id?: "1370424763823308807"
          author_id?: "151861092" 
          in_reply_to_user_id: "303364784"
          language?: "en" 
          created_at?: "2021-03-12T17:29:50.000Z"
          text: "@strikeralley Finally upgraded from my original pixel just a couple months ago - I hate switching phones. And yeah - way too expensive."
          id: "1370426823172104197"
  - 
    id: 2
    name: "Angular JS Directives"
    session_description: "One of the difficult things to manage and scale is behavior related to DOM elements. See how Angular JS allows you to separate behavior into cohesive objects that can be easily applied to DOM elements."
    level: "200"
    location_id: 1
    event_slot_name: "4:30 PM - 5:30 PM"
    event_slot_id: 5
    speaker: 
      event_id: 1
      participant_id: 1
      image_url: "https://cdn.shopify.com/s/files/1/0275/1610/8874/files/Richmond_8_b.JPG?v=1604140292"
      speaker_bio: "Joel's Bio here"
      speaker_url: "https://caspershotdogs.com/"
      twitter_handle: "@CaspersJ"
      name: "Joel Caspers"
      email: "joelcaspers@gmail.com"
      tweets: 
        -
          conversation_id?: "1370424763823308807"
          author_id?: "151861092" 
          in_reply_to_user_id: "303364784"
          language?: "en" 
          created_at?: "2021-03-12T18:06:19.000Z"
          text: "@strikeralley Completely agree, especially for the amount they charge for the phones."
          id: "1370436004163817472"
        -
          conversation_id?: "1370424763823308807"
          author_id?: "151861092" 
          in_reply_to_user_id: "303364784"
          language?: "en" 
          created_at?: "2021-03-12T17:29:50.000Z"
          text: "@strikeralley Finally upgraded from my original pixel just a couple months ago - I hate switching phones. And yeah - way too expensive."
          id: "1370426823172104197"

