#%RAML 1.0
title: iowacodecamp-papi

version: v1
description: IowaCodeCamp.com orchestration layer
baseUri: /papi/iowacodecamp/{version}

protocols: [ HTTPS ]

mediaType: [ application/json ]

types:
  Error: !include data-type/error.raml
  Session: !include data-type/session.raml

resourceTypes: 
  collection: !include resource/collection.raml
  member: !include resource/member.raml
  
/sessions:
  description: Sessions collection
  type:
    collection:
      type-name: Session  
      success-example-collection: !include example/sessions.raml
      error-type-name: Error
      errors-example: !include example/error.raml
  get:  